export const READ_NOTIFICATIONS = "READ_NOTIFICATIONS";
export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";
export const START_NOTIFICATIONS_RELOAD = "START_NOTIFICATIONS_RELOAD";
export const FINISHED_NOTIFICATIONS_RELOAD = "FINISHED_NOTIFICATIONS_RELOAD";
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
