import React from "react";
import { StyleSheet, useWindowDimensions, Platform } from "react-native";
export const checkIfMobile = (width, height) => {
  if (height / width < 0.5) {
    return true;
  } else {
    return false;
  }
};
export const globalStyle = () => {
  const { width: windowWidth, height: windowHeight } = useWindowDimensions();
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F8F8F8",
      height: "100%",
      width: "100%",
    },
    splitContainer: {
      flex: 1,
      backgroundColor: "#F8F8F8",
      height: "100%",
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    partContainer: {
      width: "50%",
      height: "100%",
      paddingVertical: "4%",
      paddingHorizontal: "2%",
    },
    loginView: {
      backgroundColor: "#F8F8F8",
    },
    logoView: {
      backgroundColor: "#4E7D9B",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },

    logoCard: {
      backgroundColor: "#F8F8F8",
      width: windowWidth * 0.2,
      height: windowWidth * 0.2,
      borderRadius: windowWidth * 0.005,
      shadowOffset: {
        width: 10,
        height: 10,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
      justifyContent: "center",
      alignItems: "center",
    },
    languageButtonsContainer: {
      position: "absolute",
      right: 0,
      top: "7%",
      flexDirection: "row",
      width: "75%",
      justifyContent: "space-evenly",
    },
    englishButton: {
      backgroundColor: "#F8F8F8",
      width: checkIfMobile(windowWidth, windowHeight)
        ? windowHeight * 0.25
        : windowHeight * 0.15,
      height: 50,
      alignItems: "center",
      justifyContent: "center",
      shadowOffset: {
        width: 10,
        height: 10,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
    },
    arabicButton: {
      width: checkIfMobile(windowWidth, windowHeight)
        ? windowHeight * 0.25
        : windowHeight * 0.15,
      height: 50,
      borderColor: "#F8F8F8",
      borderWidth: 1.5,
      alignItems: "center",
      justifyContent: "center",
    },
    loginButton: {
      height: 55,
      width: "75%",
      backgroundColor: "#4E7D9B",
      alignItems: "center",
      justifyContent: "center",

      flexDirection: "row",
      borderRadius: 8,
    },
    shadow: {
      shadowOffset: {
        width: 5,
        height: 5,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.1,
      elevation: 2,
    },
    flexBetween: {
      width: "100%",
      justifyContent: "space-between",
      alignItems: "center",
      flexDirection: "row",
    },
    flexCenter: {
      width: "100%",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
    },
    flexStart: {
      width: "100%",
      justifyContent: "flex-start",
      alignItems: "center",
      flexDirection: "row",
    },
    bodyContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 50,
      width: "100%",
      height: "100%",
      backgroundColor: "#F8F8F8",
    },
    body: {
      alignItems: "center",
      width: "90%",
      paddingBottom: 200,
      height: "100%",
      backgroundColor: "#F8F8F8",
    },
    scrollContainer: {
      height: "65%",
      alignItems: "center",
      justifyContent: "center",
    },
    btnContainer: {
      backgroundColor: "#212121",
      color: "black",
      width: "100%",
      textAlign: "center",
      fontWeight: "bold",
      padding: 10,
      borderRadius: 10,
      marginVertical: 5,
    },
    btn: {
      color: "white",
      fontWeight: "700",
      paddingVertical: 10,
      textAlign: "center",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
    },
    inputContainer: {
      alignItems: "center",
      marginVertical: 15,
      flexDirection: "row",
      width: "100%",
      justifyContent: "space-between",
    },
    fullInput: {
      fontSize: 14,
      fontWeight: "600",
      color: "#777",
      borderColor: "#F8F8F8", // if you need
      padding: 5,
      paddingHorizontal: 10,
      width: "100%",
      height: 50,
      borderRadius: 5,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
      backgroundColor: "white",
      borderWidth: 1,
    },
    smallInput: {
      fontSize: 13,
      fontWeight: "600",
      color: "#777",
      borderColor: "#F8F8F8", // if you need
      padding: 5,
      paddingHorizontal: 10,
      width: "48%",
      height: 50,
      borderWidth: 1,
      borderRadius: 5,
      backgroundColor: "white",
      borderRadius: 5,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
    },
    circle: {
      width: 37,
      height: 37,
      borderRadius: 18,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
      borderWidth: 1,
      borderColor: "#9991",
    },
    circleActiveContainer: {
      width: 50,
      height: 50,
      borderRadius: 25,
      borderWidth: 4,
      alignItems: "center",
      justifyContent: "center",
      borderColor: "#212121",
      margin: 3,
    },
    circleInActiveContainer: {
      width: 50,
      height: 50,
      borderRadius: 25,
      alignItems: "center",
      justifyContent: "center",
      margin: 3,
    },
    chooseImageBtn: {
      borderWidth: 1,
      width: 100,
      height: 100,
      borderRadius: 50,
      marginBottom: 15,
      alignItems: "center",
      justifyContent: "center",
    },
    inputAndroid: {
      paddingTop: 13,
      paddingHorizontal: 10,
      paddingBottom: 12,
      borderWidth: 1,
      borderColor: "#F8F8F8",
      borderRadius: 5,
      backgroundColor: "white",
      fontWeight: "bold",
      fontSize: 13,
      fontWeight: "600",
      color: "#777",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
      width: windowWidth * 0.9,
      height: 50,
    },
    inputIOS: {
      paddingTop: 13,
      paddingHorizontal: 10,
      paddingBottom: 12,
      borderWidth: 1,
      borderColor: "#F8F8F8",
      borderRadius: 4,
      backgroundColor: "white",
      width: windowWidth * 0.9,
      fontSize: 13,
      fontWeight: "bold",
      color: "#777",
      borderRadius: 5,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
    },
    placeholder: {
      fontSize: 13,
      fontWeight: "bold",
      color: "#777",
    },
    selectServicesContainer: {
      width: "100%",
      flexWrap: "wrap",
      flexDirection: "row",
      justifyContent: "space-between",
      marginVertical: 25,
    },
    selectServicesCard: {
      width: "48%",

      marginVertical: 10,
      backgroundColor: "white",
      borderRadius: 5,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: "#212121",
      shadowOpacity: 0.11,
      elevation: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    selectServicesText: {
      paddingVertical: 10,
    },
    selectServicesHeader: {
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      backgroundColor: "#212121",
      width: "100%",
    },
    activeSelectServicesHeader: {
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      backgroundColor: "green",
      width: "100%",
    },

    modalView: {
      width: windowWidth * 0.9,
      height: 600,
      backgroundColor: "#F8F8F8",
      borderRadius: 20,
      // padding: 35,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalHeader: {
      backgroundColor: "#212121",
      width: "100%",
      paddingVertical: 20,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalHeaderText: {
      color: "#F8F8F8",
      fontWeight: "bold",
    },
    modalBody: {
      alignItems: "center",
      justifyContent: "center",
      width: "90%",
      marginVertical: 15,
      paddingBottom: 300,
    },
    modalFooter: {
      width: "100%",
      position: "absolute",
      bottom: 0,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      backgroundColor: "#F8F8F8",
      height: 60,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },

    button: {
      borderRadius: 20,
      padding: 10,
      elevation: 2,
    },
    buttonChoose: {
      width: "50%",
      alignItems: "center",
      borderBottomRightRadius: 20,
      backgroundColor: "#212121",
      height: 60,
      justifyContent: "center",
    },
    buttonClose: {
      width: "50%",
      alignItems: "center",
      borderBottomLeftRadius: 20,
      height: 60,
      backgroundColor: "#9992",
      justifyContent: "center",
    },
    textStyle: {
      color: "white",
      fontWeight: "bold",
      textAlign: "center",
    },
    modalText: {
      marginBottom: 15,
      textAlign: "center",
    },

    card: {
      flex: 1,
      marginVertical: 4,
      marginHorizontal: 16,
      borderRadius: 5,
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
      height: "100%",
      borderColor: "black",
      borderRadius: 15,
    },
  });
};
